### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by Opussci** [igkuzm/wordgrinder#1]
Hi, I’m very intrigued in testing this tool. DOCX support is what interests me. Could you kindly tell me what is the proposed way to install it on Windows?

**Comment by igkuzm** [comment]
Hello. I have no windows and didn’t test it. But I think it should work, because it is a fork of https://github.com/davidgiven/wordgrinder

**Comment by Opussci** [comment]
So, it seems that I only need to run Windows installer [windows-installer.nsi] I will close this issue and let you know if I encounter any issues on Windows.
